// Bakes the Yale Bright Star Catalogue into a module the sky can import.
//
//   node scripts/build-sky.cjs                    # measure, write nothing
//   node scripts/build-sky.cjs --apply            # rewrite src/lib/bsc.js
//   node scripts/build-sky.cjs --from bsc5.json   # from a local copy
//
// The catalogue is every star the naked eye can reach — complete to about
// magnitude 6.5, 9,096 of them with a usable position and brightness — at
// J2000. Precession is not applied anywhere: it moves a star by half a degree
// in a lifetime, and the sky here is drawn at a scale where half a degree is
// three pixels a century from now.
//
// It is fetched rather than committed because the source is a megabyte of
// sexagesimal strings and colour temperatures, and this keeps four bytes of it.
//
// ── What is kept, and how ──────────────────────────────────────────────────
//
// Right ascension to sixteen bits is 20 arcseconds, declination to sixteen is
// 10, and the sky is drawn on a lens where a whole arcminute is a hundredth of
// a pixel. Magnitude to a fortieth is finer than the catalogue's own agreement
// with itself.
//
// Stored in columns rather than as records, and sorted by right ascension so
// that column can be varint deltas. This is not premature: measured on the real
// catalogue, records are 60,640 bytes of base64 that gzip to 45,651, and the
// columns are 48,512 that gzip to 34,601. Eleven kilobytes on the wire for
// twenty lines of packing.

const fs = require("fs");
const path = require("path");
const zlib = require("zlib");

const SOURCE =
  "https://raw.githubusercontent.com/brettonw/YaleBrightStarCatalog/master/bsc5-short.json";
const OUT = path.join(__dirname, "../src/lib/bsc.js");

const apply = process.argv.includes("--apply");
const fromAt = process.argv.indexOf("--from");
const from = fromAt >= 0 ? process.argv[fromAt + 1] : null;

// ── Reading the catalogue ──────────────────────────────────────────────────

// "00h 05m 09.9s" and "+45° 13′ 45″". The catalogue carries a few hundred
// entries that are novae, clusters, or stars since found not to exist; they are
// present with an HR number and nothing else, and they are what these fail on.
const RA = /^(\d+)h\s*(\d+)m\s*([\d.]+)s$/;
const DEC = /^([+-])(\d+)°\s*(\d+)′\s*([\d.]+)″$/;

function read(entries) {
  const stars = [];
  for (const entry of entries) {
    const ra = String(entry.RA ?? "").match(RA);
    const dec = String(entry.Dec ?? "").match(DEC);
    const mag = parseFloat(entry.V);
    if (!ra || !dec || !isFinite(mag)) continue;
    stars.push({
      // Hours to degrees, because everything downstream of here is a longitude.
      ra: (+ra[1] + +ra[2] / 60 + +ra[3] / 3600) * 15,
      dec: (dec[1] === "-" ? -1 : 1) * (+dec[2] + +dec[3] / 60 + +dec[4] / 3600),
      mag,
    });
  }
  return stars;
}

// ── Packing ────────────────────────────────────────────────────────────────

const MAG_BASE = -2; // Below Sirius at -1.46, so nothing clips at the bright end.
const MAG_STEP = 0.04;

function pack(stars) {
  stars.sort((a, b) => a.ra - b.ra);

  const ra = [];
  let previous = 0;
  for (const star of stars) {
    const tick = Math.round((star.ra / 360) * 65536) % 65536;
    let delta = tick - previous;
    previous = tick;
    // Unsigned varint: the list is sorted, so no delta is ever negative.
    while (delta > 127) {
      ra.push((delta & 127) | 128);
      delta >>>= 7;
    }
    ra.push(delta);
  }

  const dec = Buffer.alloc(stars.length * 2);
  const mag = Buffer.alloc(stars.length);
  stars.forEach((star, i) => {
    dec.writeInt16LE(Math.round((star.dec / 90) * 32767), i * 2);
    mag[i] = Math.max(0, Math.min(255, Math.round((star.mag - MAG_BASE) / MAG_STEP)));
  });

  return Buffer.concat([Buffer.from(ra), dec, mag]);
}

// ── Writing ────────────────────────────────────────────────────────────────

const module_ = (stars, packed) => `// Generated by scripts/build-sky.cjs — do not edit.
//
// The Yale Bright Star Catalogue: every star to about magnitude 6.5, at J2000.
// Right ascension and declination in sixteen bits each, visual magnitude in
// eight. See the script for the packing and for why it is columns.

export const SKY_COUNT = ${stars.length};

// Right ascension first, as varint deltas of a sixteenth-of-a-degree tick,
// sorted ascending; then declination as signed sixteens; then magnitude.
const CATALOGUE =
  ${JSON.stringify(packed.toString("base64"))};

const MAG_BASE = ${MAG_BASE};
const MAG_STEP = ${MAG_STEP};

let unpacked = null;

/**
 * The catalogue, as three parallel arrays.
 *
 * Unpacked once, on the first sky drawn rather than at import: a reader who
 * never opens the globe, or who is on the light medium where there is no sky,
 * pays only for the bytes.
 *
 * \`ra\` and \`dec\` are degrees; \`mag\` is visual magnitude, and smaller is
 * brighter, as it has been since Hipparchus.
 */
export function catalogue() {
  if (unpacked) return unpacked;

  const binary = atob(CATALOGUE);
  const ra = new Float32Array(SKY_COUNT);
  const dec = new Float32Array(SKY_COUNT);
  const mag = new Float32Array(SKY_COUNT);

  let at = 0;
  let tick = 0;
  for (let i = 0; i < SKY_COUNT; i++) {
    let delta = 0;
    let shift = 0;
    for (;;) {
      const byte = binary.charCodeAt(at++);
      delta |= (byte & 127) << shift;
      if ((byte & 128) === 0) break;
      shift += 7;
    }
    tick += delta;
    ra[i] = (tick / 65536) * 360;
  }
  for (let i = 0; i < SKY_COUNT; i++) {
    // Little-endian signed, out of two characters of a binary string.
    const low = binary.charCodeAt(at + i * 2);
    const high = binary.charCodeAt(at + i * 2 + 1);
    const word = low | (high << 8);
    dec[i] = ((word > 32767 ? word - 65536 : word) / 32767) * 90;
  }
  at += SKY_COUNT * 2;
  for (let i = 0; i < SKY_COUNT; i++) mag[i] = MAG_BASE + binary.charCodeAt(at + i) * MAG_STEP;

  unpacked = { ra, dec, mag };
  return unpacked;
}
`;

(async () => {
  const text = from
    ? fs.readFileSync(from, "utf8")
    : await fetch(SOURCE).then((r) => {
        if (!r.ok) throw new Error(`${SOURCE}: ${r.status}`);
        return r.text();
      });

  const stars = read(JSON.parse(text));
  const packed = pack(stars);
  const source = module_(stars, packed);

  const brightest = stars.reduce((a, b) => (a.mag < b.mag ? a : b));
  console.log(`stars      ${stars.length}`);
  console.log(`brightest  ${brightest.mag} at ${brightest.ra.toFixed(3)}, ${brightest.dec.toFixed(3)}`);
  console.log(`faintest   ${stars.reduce((a, b) => (a.mag > b.mag ? a : b)).mag}`);
  console.log(`packed     ${packed.length} bytes`);
  console.log(`module     ${source.length} bytes, ${zlib.gzipSync(source).length} gzipped`);

  if (!apply) {
    console.log("\n(measure only; pass --apply to write src/lib/bsc.js)");
    return;
  }
  fs.writeFileSync(OUT, source);
  console.log(`\nwrote ${path.relative(process.cwd(), OUT)}`);
})();
